name: Dispatch Image Builds

on:
  workflow_dispatch:
  push:
    branches: [trench]
    paths:
      - "flake.nix"
      - "flake.lock"

jobs:
  build-all:
    uses: ./.github/workflows/build-all.yml
    secrets: inherit
