name: Test / Nix

on:
  workflow_dispatch:
  workflow_call:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest
    steps:
      - uses: actions/checkout@v4

      - name: Check nix flake
        run: nix flake check
