name: Test / Nix

on:
  workflow_dispatch:
  workflow_call:

jobs:
  nix-build:
    runs-on: general-intelligence-systems/nix-for-github-actions
    steps:
      - uses: actions/checkout@v4

      - name: Check nix flake
        run: nix flake check
