name: Test / Nix

on:
  workflow_dispatch:
  workflow_call:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31.10.0
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check nix flake
        run: nix flake check
